baseURL = "https://haru0017.github.io/blog/"
languageCode = "ja-jp"
title = "週休五日"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  defaultTheme = "auto"
  disableThemeToggle = true
  disableSpecial1stPost = true
  googleAnalytics = "G-S7L55YTC7R"
